"""All static / constant variables used throughout Backtesting System."""

from typing import List

from sql_infra.universal_vars import DEFAULT_COLUMNS_LIST, INTRADAY_COLUMNS_LIST

# ----------------------------------------------------------------------------------------------------------------------
ALL_MARKET_DATES: List[str] = [
    "market_timestamp TEXT NOT NULL",
]
ALL_MARKET_DATES: List[str] = DEFAULT_COLUMNS_LIST + ALL_MARKET_DATES
# ----------------------------------------------------------------------------------------------------------------------
BACKTESTING_INTRADAY: List[str] = INTRADAY_COLUMNS_LIST
# ----------------------------------------------------------------------------------------------------------------------
TARGET_VARS: List[str] = [
    "time_sin NUMERIC(5,4)",
    "time_cos NUMERIC(5,4)",
    "predict_5 INTEGER",
    "predict_15 INTEGER",
    "predict_30 INTEGER",
    "predict_60 INTEGER",
    "prev_5 INTEGER",
    "prev_15 INTEGER",
    "prev_30 INTEGER",
    "prev_60 INTEGER",
    "open_5 NUMERIC(10,2)",
    "high_5 NUMERIC(10,2)",
    "low_5 NUMERIC(10,2)",
    "close_5 NUMERIC(10,2)",
    "open_15 NUMERIC(10,2)",
    "high_15 NUMERIC(10,2)",
    "low_15 NUMERIC(10,2)",
    "close_15 NUMERIC(10,2)",
    "open_30 NUMERIC(10,2)",
    "high_30 NUMERIC(10,2)",
    "low_30 NUMERIC(10,2)",
    "close_30 NUMERIC(10,2)",
    "open_60 NUMERIC(10,2)",
    "high_60 NUMERIC(10,2)",
    "low_60 NUMERIC(10,2)",
    "close_60 NUMERIC(10,2)",
    "prev_open_5 NUMERIC(10,2)",
    "prev_high_5 NUMERIC(10,2)",
    "prev_low_5 NUMERIC(10,2)",
    "prev_close_5 NUMERIC(10,2)",
    "prev_open_15 NUMERIC(10,2)",
    "prev_high_15 NUMERIC(10,2)",
    "prev_low_15 NUMERIC(10,2)",
    "prev_close_15 NUMERIC(10,2)",
    "prev_open_30 NUMERIC(10,2)",
    "prev_high_30 NUMERIC(10,2)",
    "prev_low_30 NUMERIC(10,2)",
    "prev_close_30 NUMERIC(10,2)",
    "prev_open_60 NUMERIC(10,2)",
    "prev_high_60 NUMERIC(10,2)",
    "prev_low_60 NUMERIC(10,2)",
    "prev_close_60 NUMERIC(10,2)",
]
TARGET_VARS: List[str] = INTRADAY_COLUMNS_LIST + TARGET_VARS
# ----------------------------------------------------------------------------------------------------------------------
MODEL_FEATURES: List[str] = [
    # NOTE: Single calcs
    # `dags/algo_metrics/trade_methods/noise.py`
    "efficiency_ratio NUMERIC(3,2) NOT NULL",
    "price_density_tanh NUMERIC(4,3) NOT NULL",
    "fractal_dimension NUMERIC(3,2) NOT NULL",
    # `dags/algo_metrics/trade_methods/momentums.py`
    "momentum_divergence INTEGER NOT NULL",
    # `dags/algo_metrics/trade_methods/regression_analysis.py`
    "is_upward_trend INTEGER NOT NULL",
    "trend_line_pass INTEGER NOT NULL",
    "trade_signal INTEGER NOT NULL",
    # NOTE: Range Calcs
    # `dags/algo_metrics/trade_methods/adaptive_techniques.py`
    "chande_dynamic INTEGER NOT NULL",
    "ehlers_mama_fama NUMERIC(2,1) NOT NULL",
    "ehlers_frama INTEGER NOT NULL",
    "mcginley_dynamic INTEGER NOT NULL",
    "kaufman_efficiency INTEGER NOT NULL",
    "dynamic_momentum_tanh NUMERIC(4,3) NOT NULL",
    "adaptive_trend INTEGER NOT NULL",
    # `dags/algo_metrics/trade_methods/advanced_techniques.py`
    "bierovic_true_range INTEGER NOT NULL",
    "conners_vix_reversal INTEGER NOT NULL",
    "bookstaber_volatility_breakout INTEGER NOT NULL",
    "fractal_patterns INTEGER NOT NULL",
    # `dags/algo_metrics/trade_methods/behavioral.py`
    "vol_ratio INTEGER NOT NULL",
    "vol_ratio_tanh NUMERIC(4,3) NOT NULL",
    # `dags/algo_metrics/trade_methods/charting.py`
    "detect_spike INTEGER NOT NULL",
    "island_reversal INTEGER NOT NULL",
    "pivot_point_top INTEGER NOT NULL",
    "pivot_point_low INTEGER NOT NULL",
    "pivot_point_volatile INTEGER NOT NULL",
    "pivot_point_buy INTEGER NOT NULL",
    "pivot_point_sell INTEGER NOT NULL",
    "reversal_day INTEGER NOT NULL",
    "key_reversal_down INTEGER NOT NULL",
    "key_reversal_up INTEGER NOT NULL",
    "wide_range_day INTEGER NOT NULL",
    "outside_day INTEGER NOT NULL",
    "inside_day INTEGER NOT NULL",
    "doji INTEGER NOT NULL",
    "double_doji INTEGER NOT NULL",
    "engulfing_pattern INTEGER NOT NULL",
    # `dags/algo_metrics/trade_methods/cycles.py`
    "hilbert_transform NUMERIC(2,1) NOT NULL",
    "fisher_transform_signal INTEGER NOT NULL",
    "fisher_transform_tanh NUMERIC(4,3) NOT NULL",
    "ehlers_universal_tanh NUMERIC(4,3) NOT NULL",
    "short_cycle INTEGER NOT NULL",
    # `dags/algo_metrics/trade_methods/day_trading.py`
    "first_hour_breakout INTEGER NOT NULL",
    "momentum_pinball INTEGER NOT NULL",
    "raschke_range_breakout INTEGER NOT NULL",
    "williams_range_breakout INTEGER NOT NULL",
    "williams_second_method INTEGER NOT NULL",
    "true_upward_gap INTEGER NOT NULL",
    "intraday_sell_shock INTEGER NOT NULL",
    "intraday_buy_shock INTEGER NOT NULL",
    # `dags/algo_metrics/trade_methods/event_driven.py`
    "swing_high_low INTEGER NOT NULL",
    "swing_high_low_entry INTEGER NOT NULL",
    "wilder_swing_index INTEGER NOT NULL",
    "n_day_breakout INTEGER NOT NULL",
    "turtle_strategy_enter INTEGER NOT NULL",
    "turtle_strategy_exit INTEGER NOT NULL",
    "turtle_strategy_net_position INTEGER NOT NULL",
    "turtle_strategy_stop INTEGER NOT NULL",
    "turtle_strategy_net_stop INTEGER NOT NULL",
    # `dags/algo_metrics/trade_methods/momentums.py`
    "div_index_slow INTEGER NOT NULL",
    "div_index_fast INTEGER NOT NULL",
    "ultim_osc_1 INTEGER NOT NULL",
    "ultim_osc_2 INTEGER NOT NULL",
    "relative_vigor_idx INTEGER NOT NULL",
    "relative_vigor_idx_tanh NUMERIC(4,3) NOT NULL",
    "raschke_first_cross INTEGER NOT NULL",
    "strength_oscillator_tanh NUMERIC(4,3) NOT NULL",
    "velocity_accel NUMERIC(3,2) NOT NULL",
    "cambridge_hook INTEGER NOT NULL",
    # `dags/algo_metrics/trade_methods/multi_time_frames.py`
    "elder_triple_intraday_timing INTEGER NOT NULL",
    "elder_triple_force_index INTEGER NOT NULL",
    "elder_triple_ray INTEGER NOT NULL",
    # `dags/algo_metrics/trade_methods/price_distribution.py`
    "kase_devstop NUMERIC(3,2) NOT NULL",
    "jackson_zone NUMERIC(3,2) NOT NULL",
    "chande_kroll_zone NUMERIC(2,1) NOT NULL",
    "scorpio_zone NUMERIC(3,2) NOT NULL",
    "mcnicholl_skewness_tanh NUMERIC(4,3) NOT NULL",
    "skew_kurt_volatility INTEGER NOT NULL",
    # `dags/algo_metrics/trade_methods/trends.py`
    "smooth_expon_single INTEGER NOT NULL",
    "smooth_expon_double INTEGER NOT NULL",
    "simple_volatility INTEGER NOT NULL",
    "single_system_momentum INTEGER NOT NULL",
    "single_system_mov_avg INTEGER NOT NULL",
    "single_system_exponential INTEGER NOT NULL",
    "single_system_slope INTEGER NOT NULL",
    "single_system_n_day_breakout INTEGER NOT NULL",
    "donchian_5_20 INTEGER NOT NULL",
    "golden_cross INTEGER NOT NULL",
    "woodshedder_long_term INTEGER NOT NULL",
    "three_crossover INTEGER NOT NULL",
    "ehlers_onset NUMERIC(3,2) NOT NULL",
    "trix_signal INTEGER NOT NULL",
    "kestner_adx INTEGER NOT NULL",
    "donchian_breakout INTEGER NOT NULL",
    # `dags/algo_metrics/trade_methods/volumes.py`
    "volume_price_combo NUMERIC(2,1) NOT NULL",
    "mcclellan_oscillator_tanh NUMERIC(4,3) NOT NULL",
    "volume_spike INTEGER NOT NULL",
    "pseudo_volume INTEGER NOT NULL",
    "low_volume_period INTEGER NOT NULL",
    "low_price_move INTEGER NOT NULL",
    # `dags/algo_metrics/tech_analysis/momentum.py`
    "relative_strength_index NUMERIC(3,2) NOT NULL",
    "true_strength_index NUMERIC(3,2) NOT NULL",
    "stoch_osc_k NUMERIC(3,2) NOT NULL",
    "stoch_osc_d NUMERIC(3,2) NOT NULL",
    "stoch_osc_d_slow NUMERIC(3,2) NOT NULL",
    "kaufman_adapt_dynamic INTEGER NOT NULL",
    "kaufman_adapt_regular INTEGER NOT NULL",
    "rate_of_change_tanh NUMERIC(4,3) NOT NULL",
    "williams_perc_r NUMERIC(3,2) NOT NULL",
    "stoch_rsi NUMERIC(3,2) NOT NULL",
    "stoch_rsi_k NUMERIC(3,2) NOT NULL",
    "stoch_rsi_d NUMERIC(3,2) NOT NULL",
    "perc_price_osc_tanh NUMERIC(4,3) NOT NULL",
    "perc_price_osc_signal_tanh NUMERIC(4,3) NOT NULL",
    "perc_price_osc_hist_tanh NUMERIC(4,3) NOT NULL",
    "perc_volume_osc_tanh NUMERIC(4,3) NOT NULL",
    "perc_volume_osc_signal_tanh NUMERIC(4,3) NOT NULL",
    "perc_volume_osc_hist_tanh NUMERIC(4,3) NOT NULL",
    "awesome_osc_tanh NUMERIC(4,3) NOT NULL",
    # `dags/algo_metrics/tech_analysis/trend.py`
    "aroon_up NUMERIC(3,2) NOT NULL",
    "aroon_down NUMERIC(3,2) NOT NULL",
    "aroon_indicator NUMERIC(3,2) NOT NULL",
    "adx_signal NUMERIC(3,2) NOT NULL",
    "adx_pos_signal NUMERIC(3,2) NOT NULL",
    "adx_neg_signal NUMERIC(3,2) NOT NULL",
    "macd_tanh NUMERIC(4,3) NOT NULL",
    "macd_signal_tanh NUMERIC(4,3) NOT NULL",
    "macd_diff_tanh NUMERIC(4,3) NOT NULL",
    "ichimoku_span INTEGER NOT NULL",
    "ichimoku_close INTEGER NOT NULL",
    "ichimoku_base INTEGER NOT NULL",
    "kst_tanh NUMERIC(4,3) NOT NULL",
    "kst_signal_tanh NUMERIC(4,3) NOT NULL",
    "kst_diff_tanh NUMERIC(4,3) NOT NULL",
    "detrend_price_osc_tanh NUMERIC(4,3) NOT NULL",
    "cci_tanh NUMERIC(4,3) NOT NULL",
    "vortex_diff_tanh NUMERIC(4,3) NOT NULL",
    "psar_up_indicator INTEGER NOT NULL",
    "psar_down_indicator INTEGER NOT NULL",
    "schaff_trend_cycle NUMERIC(3,2) NOT NULL",
    # `dags/algo_metrics/tech_analysis/volatility.py`
    "bollinger_bands_high INTEGER NOT NULL",
    "bollinger_bands_low INTEGER NOT NULL",
    "keltner_channel_high INTEGER NOT NULL",
    "keltner_channel_low INTEGER NOT NULL",
    "donchian_channel_perc_band NUMERIC(3,2) NOT NULL",
    "ulcer_index_tanh NUMERIC(4,3) NOT NULL",
    "bookstaber_std_dev_tanh NUMERIC(4,3) NOT NULL",
    "bookstaber_log_squared_tanh NUMERIC(4,3) NOT NULL",
    "bookstaber_high_low_tanh NUMERIC(4,3) NOT NULL",
    # `dags/algo_metrics/tech_analysis/volume.py`
    "chaikin_money_flow NUMERIC(3,2) NOT NULL",
    "force_index_tanh NUMERIC(4,3) NOT NULL",
    "ease_of_move_tanh NUMERIC(4,3) NOT NULL",
    "ease_of_move_sma_tanh NUMERIC(4,3) NOT NULL",
    "money_flow_index NUMERIC(3,2) NOT NULL",
    # NOTE: The `sine` & `cosine` Time Of Day Variables
    "time_sin NUMERIC(5,4)",
    "time_cos NUMERIC(5,4)",
    # NOTE: The Prediction Variables
    "predict_5 INTEGER",
    "predict_15 INTEGER",
    "predict_30 INTEGER",
    "predict_60 INTEGER",
]
MODEL_FEATURES: List[str] = INTRADAY_COLUMNS_LIST + MODEL_FEATURES
